SEED: 42
num_classes: 10
data_name: cifar10
train_algo: &algo bt-sc
data_params:
  algo: *algo
  data_dir: datasets/cifar10
  batch_size: 512
  num_workers: 3
  image_size: 32
return_logs: False
eval_every: 10
n_epochs: &epoch 800
n_epochs_mlp: 100
gpu_id: 3
opt: SGD
opt_params:
  lr: !!float 4e-1
  momentum: 0.9
  weight_decay: !!float 1e-4
# schedular_params:
#   step_size: 40 
#   gamma: 0.1
schedular_params:
  T_max: *epoch 
  eta_min: 0.001
mlp_opt: SGD
mlp_opt_params:
  lr: !!float 0.01
  momentum: 0.9
energy_model_params:
  eta: !!float 1e-2
  steps: 5
  sigma: !!float 2e-1
  delta: !!float 1e-1
  net_type: energy
energy_opt: AdamW
energy_model_opt_params:
  lr: !!float 1e-3
warmup_epochs: 0
model_params:
  model_name: 'resnet18' 
  pretrained: False 
  proj_dim: 4096
  barlow_hidden: 4096
  algo_type: *algo 
mlp_type: "hidden"
loss: *algo
loss_params: 
  lambd: 0.005
distributed: False
model_save_path: saved_models