SEED: 42
train_algo: &algo byol
dataset: 
  cifar10: 
    num_classes: 10
    params: 
      data_dir: datasets/cifar10
      batch_size: 512
      num_workers: 3
      image_size: 32
      algo: *algo 
  cifar100: 
    num_classes: 100
    params: 
      data_dir: datasets/cifar100
      batch_size: 512
      num_workers: 3
      image_size: 32
      algo: *algo
return_logs: False
eval_every: 10
n_epochs: &epoch 800
n_epochs_mlp: 100
gpu_id: 5
opt: SGD
opt_params:
  lr: !!float 4e-1
  momentum: 0.9
  weight_decay: !!float 5e-4 # 1e-4 for c100 
# schedular_params:
#   step_size: 40 
#   gamma: 0.1
schedular_params:
  T_max: *epoch 
  eta_min: 0.001
mlp_opt: SGD
mlp_opt_params:
  lr: !!float 0.01
  momentum: 0.9
model_params:
  model_name: 'resnet18' 
  pretrained: False 
  proj_dim: 256
  algo_type: *algo
  byol_hidden: 4096
  pred_dim: 256
ema_tau: 0.996
mlp_type: "hidden"
loss: *algo
distributed: False
model_save_path: saved_models
