SEED: 42
num_classes: 10
data_name: cifar10
data_params:
  algo: scalre
  data_dir: datasets/cifar10
  batch_size: 512
  num_workers: 3
  image_size: 32
return_logs: False
eval_every: 10
n_epochs: &epoch 600
n_epochs_mlp: 100
gpu_id: 1
opt: SGD
opt_params:
  lr: !!float 5e-1
  momentum: 0.9
  nesterov: True
# schedular_params:
#   step_size: 40 
#   gamma: 0.1
schedular_params:
  T_max: *epoch 
  eta_min: 0.001
mlp_opt: SGD
mlp_opt_params:
  lr: !!float 0.01
  momentum: 0.9
  nesterov: True

energy_model_params:
  eta: !!float 1e-2
  steps: 5
  sigma: !!float 2e-1
  delta: !!float 1e-1
  net_type: energy
  
energy_opt: AdamW
energy_model_opt_params:
  lr: !!float 1e-3

model_params:
  model_name: 'resnet18' 
  pretrained: False 
  proj_dim: 128
  algo_type: scalre

mlp_type: "hidden"
loss: scalre
loss_params: 
  sim: 'cosine'
  tau: 0.5
distributed: False
train_algo: scalre

model_save_path: saved_models