SEED: 42
train_algo: &algo simclr
dataset: 
  cifar10: 
    num_classes: 10
    params: 
      data_dir: datasets/cifar10
      batch_size: 512
      num_workers: 1
      image_size: 32
      algo: *algo 
  cifar100: 
    num_classes: 100
    params: 
      data_dir: datasets/cifar100
      batch_size: 512
      num_workers: 1
      image_size: 32
      algo: *algo
return_logs: False
eval_every: 10
n_epochs: &epoch 600
n_epochs_mlp: 100
gpu_id: 1
opt: SGD
opt_params:
  lr: !!float 5e-1
  momentum: 0.9
  nesterov: True
  weight_decay: !!float 1e-4
# schedular_params:
#   step_size: 40 
#   gamma: 0.1
schedular_params:
  T_max: *epoch 
  eta_min: 0.001
mlp_opt: SGD
mlp_opt_params:
  lr: !!float 0.01
  momentum: 0.9
  nesterov: True

model_params:
  model_name: 'resnet18' 
  pretrained: False 
  proj_dim: 128
  algo_type: *algo 

mlp_type: "hidden"
loss: *algo
loss_params: 
  sim: 'cosine'
  tau: 0.5
distributed: False

model_save_path: saved_models