SEED: 42
train_algo: &algo vicreg-sc
dataset: 
  cifar10: 
    num_classes: 10
    params: 
      data_dir: datasets/cifar10
      batch_size: 512
      num_workers: 1
      image_size: 32
      algo: *algo 
  cifar100: 
    num_classes: 100
    params: 
      data_dir: datasets/cifar100
      batch_size: 512
      num_workers: 1
      image_size: 32
      algo: *algo
return_logs: False
eval_every: 10
n_epochs: &epoch 800
n_epochs_mlp: 100
gpu_id: 3
opt: SGD
opt_params:
  lr: !!float 4e-1
  momentum: 0.9
  weight_decay: !!float 1e-6
# schedular_params:
#   step_size: 40 
#   gamma: 0.1
schedular_params:
  T_max: *epoch 
  eta_min: 0.001
mlp_opt: SGD
mlp_opt_params:
  lr: !!float 0.01
  momentum: 0.9
model_params:
  model_name: 'resnet18' 
  pretrained: False 
  proj_dim: 4096
  barlow_hidden: 4096
  algo_type: *algo
mlp_type: "hidden"
loss: *algo
loss_params: 
  _lambda: 25.0
  mu: 25.0
  nu: 1.0
distributed: False
model_save_path: saved_models
energy_model_params:
  eta: !!float 1e-3
  steps: 8
  sigma: !!float 1e-1
  delta: !!float 5.0
  net_type: energy
energy_opt: AdamW
energy_model_opt_params:
  lr: !!float 3e-4
warmup_epochs: 0